### ISSUE TITLE
Auction creator can bid on its own auctions

### ISSUE THREAD

**Issue by sebyx31** [ase-15/ebay#22]

**Comment by sebyx31** [comment]
Quick & dirty fix in ef93efa40381339cc5c4bc8a4db5d4c6d6a49935.
Hide the relevant panels in Auction.show. A better fix would also prevent the action to be performed by forging the URL.

**Comment by tibm** [comment]
OK. Actually it's fine for this "demo". The thing is, I found it good to be able to bid on the own auction. Of a user point of view. Don't you think? This is more a "user centered question" and not relevant here...

**Comment by sebyx31** [comment]
Well, if you can bid on your own auction, it means that you can win it. Winning an auction means that you agree to buy the article for the amount of your bid. Buying something from yourself does not make any sense, right?

**Comment by tibm** [comment]
Of course, but my idea was:
You bid 10 for my auction
I bid 11. If you really want it then bid more. => kind of a game, but I guess you're right, just ignore what I said ;) It was more to simplify and find an argument, hehe

**Comment by tibm** [comment]
Done
