### ISSUE TITLE
Manage auction

### ISSUE THREAD

**Issue by facenord-sud** [ase-15/ebay#8]
It means the views adapted for creating and editing an auction and don't forget the image upload

A nice presentation of an auction

**Comment by sebyx31** [comment]
Done, image upload is working. 73a6aee818f49ced5dd0a316f828bd49ce299312

**Comment by tibm** [comment]
Ehm, actually I got multiple errors (on show and edit) API key is missing... Are they in the env? Is your update/show working? See the print-screens... well maybe it's late ;-) I need some sleep

![capture d ecran 2015-09-23 a 23 55 15](https://cloud.githubusercontent.com/assets/12569338/10060038/af4d1006-624e-11e5-8f87-ca976dc68e18.png)
![capture d ecran 2015-09-23 a 23 55 40](https://cloud.githubusercontent.com/assets/12569338/10060039/af6c4796-624e-11e5-976c-a855c5024616.png)

**Comment by sebyx31** [comment]
You need an API key for Cloudinary to work. You can create your own or use the config file that I posted on Hangouts. Our Heroku app is already configured for it.

**Comment by tibm** [comment]
Ok, thanks, working...
Would be nice to resize images tough (at least for the "big project")
Like: create a thumbnail (max 50x50 px) and a high-res (max 1500x1500 px) to free space. I think it's very easy with that gem isn't it? I don't know it...
